stopwords_filepath: ./custom_dicts/stopwords.txt
embedding_model_name: BAAI/bge-m3
expansion_model_path: ../word2vec/wiki.zh.bin
bm25_k1: 0.5
bm25_b: 0.7
bm25_epsilon: 0.5
use_expansion: false
expanded_topn: 2
chunk_size: 500
overlap: 100
scoring_methods:
  use_faiss: true
  use_term_importance: true
  use_semantic_search: true
  use_term_density: true
  use_query_coverage: true
  use_position_score: true
  use_context_similarity: true
base_weights:
  bm25: 0.2
  faiss: 0.3
  importance: 0.0
  semantic: 0.1
  coverage: 0.1
  position: 0.1
  density: 0.15
  context: 0.05
