FROM nvidia/cuda:12.1.0-cudnn8-devel-ubuntu22.04 as base

# Update PATH to include conda
ENV PATH="/miniconda/bin:$PATH"

# Set CUDA architecture flags
ENV TORCH_CUDA_ARCH_LIST="6.0 6.1 7.0 7.5 8.0 8.6+PTX"

# Set the working directory
WORKDIR /app

# Install vim, git, bash
RUN apt-get update && apt-get install -y vim \
    git \
    bash \
    wget \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

FROM base as teseract
# OCR Tesseract dependencies
RUN apt-get update && apt-get install -y tesseract-ocr

## Developer Tools
#RUN apt-get update && apt-get install -y libtesseract-dev

RUN apt-get update && apt-get install -y g++ \
    autoconf \
    automake \
    libtool \
    pkg-config \
    libpng-dev \
    libjpeg8-dev \
    libtiff5-dev \
    zlib1g-dev \
    libleptonica-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

### help using command line
# RUN apt-get update && apt-get install -y snap && \
#     apt-get clean && rm -rf /var/lib/apt/lists/*
# RUN snap install --channel=edge tesseract

### Install language pack
RUN apt-get update && apt-get install -y tesseract-ocr-eng \
    tesseract-ocr-chi-tra && \
    apt-get clean && rm -rf /var/lib/apt/lists/*


FROM teseract as conda

# Install miniconda
# Install dependencies and miniconda
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-py310_24.7.1-0-Linux-x86_64.sh && \
    bash Miniconda3-py310_24.7.1-0-Linux-x86_64.sh -b -p /miniconda && \
    rm Miniconda3-py310_24.7.1-0-Linux-x86_64.sh && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN conda init

FROM conda as langchain_ocr
RUN apt-get update && apt-get install -y libgl1-mesa-glx \
    poppler-utils && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
RUN conda init
# Create conda environment and install GPU versions
RUN conda config --set ssl_verify false
RUN conda update --all -y && \
    conda install -c anaconda ca-certificates -y && \
    conda install -c anaconda openssl -y

RUN conda create -n langchain_ocr python=3.10 -y

RUN conda run -n langchain_ocr pip install "unstructured[pdf]" langchain-unstructured tqdm unstructured
RUN conda run -n langchain_ocr pip install --upgrade PyMuPDF pdfminer.six

RUN echo "conda activate langchain_ocr" >> ~/.bashrc
