services:
  langchain_ocr:
    build:
      context: .
      dockerfile: dockerfile
    container_name: langchain_ocr
    volumes:
      - .:/app/ocr
      - ../CompetitionDataset:/app/CompetitionDataset
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: >
      bash -c "cd /app/ocr && conda run -n langchain_ocr bash ./preprocess.sh"
