services:
  baseline:
    image: esun/baseline
    ports:
      - "5000:5000"
    volumes:
      - ../:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    command: [ "tail", "-f", "/dev/null" ]
